# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Docker.gitlab-ci.yml

workflow:
  rules:
    # Run only for branches, not tags:
    # https://stackoverflow.com/a/68130421/624787
    - if: "$CI_COMMIT_TAG"
      when: "never"
    - when: "always"

default:
  image: "docker:latest"
  services:
    - "docker:dind"
  before_script:
    # Install packages into container required to hand off to `$ make`
    - "apk update"
    - "apk add make bash git gettext py3-pip gnupg curl github-cli"
    # Add an unprivileged user to cover those use cases and more closely match local
    # development
    - "addgroup -g $PGID runner"
    - "adduser -u $PUID -G runner -g 'CI Runner,,,' -D runner"
    # Add user installs to PATH
    - 'export PATH="/home/runner/.local/bin:$PATH"'
    # Make the checkout accessible to the user
    - "chown -R $PUID:$PGID ./"

variables:
  # Options that affect GitLab CI/CD runner behavior
  GIT_FETCH_EXTRA_FLAGS: "--tags --prune"

  # Secrets from the GitLab CI/CD Variables UI:
  CODECOV_TOKEN: "$CODECOV_TOKEN"
  DOCKER_PASS: "$DOCKER_PASS"
  GPG_PASSPHRASE: "$GPG_PASSPHRASE"
  GPG_SIGNING_PRIVATE_KEY: "$GPG_SIGNING_PRIVATE_KEY"
  PYPI_PASSWORD: "$PYPI_PASSWORD"
  TEST_PYPI_PASSWORD: "$TEST_PYPI_PASSWORD"
  GH_TOKEN: "$GH_TOKEN"

  # Change pip's cache directory to be inside the project directory since we can only
  # cache local items:
  # https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

  # Variables controlling behavior
  PUID: "1001"
  PGID: "1001"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - "./.cache/pip"
    - "./.tox"
    - "./.tox-*"

# Delegate to the `./Makefile` as much as possible to keep as much portable between CI
# platforms

stages:
  - "bump"
  - "build-test"
  - "release"

bump:
  stage: "bump"
  script:
    # Hand off the rest to `$ make` as the unprivileged user
    - "su runner -c 'make -e PYTHON_MINORS=3.11 build-bump'"

build-test:
  stage: "build-test"
  parallel:
    matrix:
      - PYTHON_MINORS:
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.7"
  script:
    - >-
      su runner -c '
          make -e PYTHON_MINORS=3.11
          build-docker-${PYTHON_MINORS} test-docker-${PYTHON_MINORS}
      '
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    # Upload build artifacts:
    # https://docs.gitlab.com/ee/ci/pipelines/job_artifacts.html
    paths:
      - "./.tox-docker/${PYTHON_MINORS}/pytest*"
      - "./.tox-docker/${PYTHON_MINORS}/coverage*"
      - "./.tox-docker/${PYTHON_MINORS}/htmlcov"
      - "./.tox-docker/${PYTHON_MINORS}/pylint*"
      - "./.tox-docker/.pkg/dist/*"
      - "./dist/*"
      - "./NEWS-release.rst"
    reports:
      junit: "./.tox-docker/${PYTHON_MINORS}/pytest-junit.xml"
      coverage_report:
        coverage_format: "cobertura"
        path: "./.tox-docker/${PYTHON_MINORS}/coverage.xml"

release:
  stage: "release"
  script:
    - "su runner -c 'make -e PYTHON_MINORS=3.11 release'"
