# Override `$ docker compose ...` configuration for development or testing here in this
# repo checkout.  Everything that may be used outside this checkout should be in
# `./docker-compose.yml`.
version: "3.8"

services:

  ## Container for use by developers
  python-project-structure.devel:
    image: "merpatterson/python-project-structure:devel"
    depends_on:
      - "python-project-structure"
    build:
      context: "./"
      dockerfile: "./Dockerfile.devel"
    volumes:
      # Ensure local changes are reflected inside the container.
      - "./:/usr/local/src/python-project-structure/"
      # Ensure access permissions to build artifacts inside docker.
      # If created by `# dockerd`, it ends up owned by `root`.
      - "./.tox-docker/:/usr/local/src/python-project-structure/.tox"
      - "./src/python_project_structure-docker.egg-info/:/usr/local/src/python-project-structure/src/python_project_structure.egg-info/"

  ## Contianers used during release

  pandoc:
    image: "pandoc/core"
    user: "${PUID:-1000}:${PGID:-100}"
    volumes:
      - "./:/data/"
    command: >-
      "./README.rst" -f "rst" -t "markdown" -o "./README.md"

  docker-pushrm:
    image: "chko/docker-pushrm"
    depends_on:
      - "pandoc"
    env_file: "./.env"
    volumes:
      - "./:/data/"
    command: >-
      --file "/data/README.md" --short "Python project structure foundation or template"
      --debug "merpatterson/python-project-structure"
