# Override `$ docker compose ...` configuration for development or testing here in this
# repo checkout.  Everything that may be used outside this checkout should be in
# `./docker-compose.yml`.
version: "3.8"

services:

  ## Configuration specific to this checkout
  python-project-structure:
    image: "merpatterson/python-project-structure:${PYTHON_ENV:-py311}-local"
    build: "./"
    volumes:
      # Preserve caches caches between container runs
      - "./home/:/home/python-project-structure/"

  ## Container for use by developers
  python-project-structure-devel:
    image: "merpatterson/python-project-structure:${PYTHON_ENV:-py311}-devel-local"
    build:
      context: "./"
      dockerfile: "./Dockerfile.devel"
    environment:
      # Make the run-time user configurable in `./.env`
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-${PUID:-1000}}"
      DEBUG: "true"
    volumes:
      # Ensure local changes are reflected inside the container.
      - "./:/usr/local/src/python-project-structure/"
      # Preserve caches caches between container runs
      - "./home/:/home/python-project-structure/"
      # Avoid any clashes between image variants and/or the local host at both build and
      # run-time.
      - "./var/docker/${PYTHON_ENV:-py311}/:/usr/local/src/python-project-structure/var/"
      - "./var/docker/${PYTHON_ENV:-py311}/.tox/:/usr/local/src/python-project-structure/.tox/"
      - "./var/docker/${PYTHON_ENV:-py311}/python_project_structure.egg-info/:/usr/local/src/python-project-structure/src/python_project_structure.egg-info/"

  ## Contianers during development and release

  # https://github.com/hadolint/hadolint#how-to-use
  hadolint:
    image: "hadolint/hadolint"
    volumes:
      - "./:/usr/local/src/python-project-structure/"
    working_dir: "/usr/local/src/python-project-structure/"

  pandoc:
    image: "pandoc/core"
    user: "${PUID:-1000}:${PGID:-${PUID:-1000}}"
    volumes:
      - "./:/data/"
    command: >-
      "./README.rst" -f "rst" -t "markdown" -o "./README.md"

  docker-pushrm:
    image: "chko/docker-pushrm"
    depends_on:
      - "pandoc"
    environment:
      DOCKER_USER: "${DOCKER_USER:-merpatterson}"
      DOCKER_PASS: "${DOCKER_PASS}"
    volumes:
      - "./:/data/"
    command: >-
      --file "/data/README.md" --short "Python project structure foundation or template"
      --debug "merpatterson/python-project-structure"

  ## Container for use by end users
  docker:
    image: "docker:latest"
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./:${CHECKOUT_DIR}"
    environment:
      DOCKER_GID: "${DOCKER_GID:-}"
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-${PUID:-1000}}"
      DEBUG: "true"
    working_dir: "${CHECKOUT_DIR}"
    entrypoint: "./bin/docker-entrypoint"
    command: >-
      make -e build-docker test-docker release
